### PR TITLE
Add more flexible assertions

### PR DESCRIPTION
**Pull request by deniskulicek**
I found current assertions to be too limiting and needed some more flexibility with partial matching and more flexible assertions in general. I Added the following functions to `Apus.Test` module to achieve that:

`assert_delivered_message/0` - checks if any message was delivered
`assert_delivered_message_matches/1` - allows custom function matching similar to what Swoosh provides with anonymous function test assertions
`refute_delivered_message/0` - refutes that any message was delivered

Docs and readme were updated to reflect the changes above, plus added some additional assertion examples.

### CODE REVIEW

**Comment by deniskulicek** [comment]
@swelham is there anything I can help with to make this easier to review/have it merged in? Cheers!

**Comment by cytex-media-solutions** [comment]
Really appreciated over here. Hope can be considered and reviewed soon :-)

**Comment by swelham** [comment]
Hey, thanks for the PR and sorry for the delay on this, having a crazy busy start to the year!

This looks good to me 👍

I will get it merged and published.

**Comment by deniskulicek** [comment]
Thanks @swelham, much appreciated! I haven't tested these changes on older Elixir version, it seems that some of the test additions now break the `build_legacy` pipeline. If the pipeline is still relevant I'll come up with a fix for it

**Pull request merged**
